### ISSUE TITLE
Sharing weights of imitation_models

### ISSUE THREAD

**Issue by GianlucaDeStefano** [LauJames/PAT#1]
Hello, thank you for the nice paper. 

I was wondering if you could share the weights of the imitation models. 
I am interested in reproducing some results, but I prefer to avoid retraining the imitation models. 

I thank you in advance :)

**Comment by LauJames** [comment]
Thank you for your interest in our work. 

Can you give me your email address to me? I will share those weights of models with you :)

**Comment by LauJames** [comment]
Thank you for your interest in our work. 

Can you give me your email address to me? I will share the weights of the models with you :)

**Comment by GianlucaDeStefano** [comment]
I've sent you an email at the [LauJames_work@163.com](mailto:LauJames_work@163.com).
