### ISSUE TITLE
msmarco_passage/runs_from_public/run.dev.sub_small.tsv file

### ISSUE THREAD

**Issue by Gerry-j** [LauJames/PAT#4]
Please，where did you download this file：msmarco_passage/runs_from_public/run.dev.sub_small.tsv ？

**Comment by LauJames** [comment]
I constructed this file by myself. It's just a subset of the run.dev.small.tsv, which can significantly improve the validation efficiency during training phase.
















At 2024-08-22 10:55:41, "Gerry-j" ***@***.***> wrote:

Please，where did you download this file：msmarco_passage/runs_from_public/run.dev.sub_small.tsv ？
